from .base import *

DEBUG = True

ALLOWED_HOSTS = [
    "100.125.157.33",
    "taila76149.ts.net",
    "localhost",
    "127.0.0.1",
]

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
