# Generated by Django 5.2 on 2025-04-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0002_customer_remove_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
