# Generated by Django 5.2 on 2025-04-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0003_component_low_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomponent',
            name='quantity_needed',
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(related_name='products', through='ungoverned_app.ProductComponent', to='ungoverned_app.component'),
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='quantity_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ungoverned_app.product'),
        ),
    ]
