# Generated by Django 5.2 on 2025-04-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0004_remove_productcomponent_quantity_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(through='ungoverned_app.ProductComponent', to='ungoverned_app.component'),
        ),
    ]
