# Generated by Django 5.2 on 2025-04-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0005_remove_product_price_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
