# Generated by Django 5.2 on 2025-04-30 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0007_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
