# Generated by Django 5.2 on 2025-05-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0013_customer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
