# Generated by Django 4.2.11 on 2026-03-04 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ungoverned_app', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='stock_quantity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('RECEIVE', 'Receive'), ('ADJUSTMENT', 'Adjustment'), ('BUILD_CONSUME', 'Build Consume'), ('BUILD_CANCEL_RETURN', 'Build Cancel Return'), ('ORDER_CANCEL_RETURN', 'Order Cancel Return')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='ungoverned_app.component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['component', '-created_at'], name='ungoverned__compone_fc8074_idx'), models.Index(fields=['reason', '-created_at'], name='ungoverned__reason_ba39ad_idx')],
            },
        ),
    ]
