# Generated by Django 4.2.11 on 2026-03-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0018_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='stock_quantity',
            field=models.IntegerField(default=0, editable=False, help_text='Managed automatically via stock movements. Use Receive Stock / Adjust Stock, not direct edits.'),
        ),
    ]
