# Generated by Django 4.2.11 on 2026-04-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0019_alter_component_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='qty_per_vehicle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='sub_assembly',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='top_level_item',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
