# Generated by Django 4.2.11 on 2026-04-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0020_component_material_component_qty_per_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='low_stock_threshold',
        ),
    ]
