# Generated by Django 4.2.11 on 2026-04-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0021_remove_component_low_stock_threshold'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('product', 'component'), name='unique_product_component'),
        ),
    ]
