# Generated by Django 4.2.11 on 2026-04-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0022_productcomponent_unique_product_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='qty_per_vehicle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy field. Use ProductComponent.quantity_required as the source of truth for BOM/build logic.', max_digits=10, null=True),
        ),
    ]
