# Generated by Django 4.2.11 on 2026-04-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0023_alter_component_qty_per_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='qty_per_vehicle',
        ),
    ]
