# Generated by Django 4.2.11 on 2026-04-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0024_remove_component_qty_per_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
