# Generated by Django 4.2.11 on 2026-04-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoverned_app', '0026_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
